# This is a basic workflow to help you get started with Actions

name: build glibc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    runs-on: self-hosted
    steps:
      - name: build glibc for aarch64
        run: docker run --rm --env STDOUT=1 langerma/glibc-builder 2.34 /usr/glibc-compat > glibc-bin-2.34-aarch64.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: glibc-bin-2.34-aarch64.tar.gz
          path: glibc-bin-2.34-aarch64.tar.gz
